
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*

COPY init-database.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN adduser --disabled-password --gecos '' dbuser
RUN chown -R dbuser:dbuser /app
USER dbuser

CMD ["python", "init-database.py"]
