services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-calculator-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/grade_calculator.db
    volumes:
      - ./data:/app/data
    networks:
      - fiap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: fiap-calculator-db
    volumes:
      - ./data:/app/data
    networks:
      - fiap-network
    restart: "no"
    environment:
      - DATABASE_URL=sqlite:///./data/grade_calculator.db

networks:
  fiap-network:
    driver: bridge

volumes:
  app-data:
    driver: local